name: ServerHub
main: me.KeybordPiano459.ServerHub.ServerHub
version: 1.1

commands:
  hub:
    description: Open up a GUI with server events
    permission: serverhub.hub

permissions:
  serverhub.*:
    description: All ServerHub perms
    default: op
    children:
      serverhub.hub: true
      serverhub.reload: true
  serverhub.hub:
    description: Access to /hub
    default: true
  serverhub.reload:
    description: Access to /hub reload
    default: op
